### PR TITLE
Added: volume control

### PR DESCRIPTION
**Pull request by vivekbharatha**
Hi @siwalikm , I loved this application and decided to add volume control.
Can you please review and accept my pull request :) #9

### CODE REVIEW

**Comment by gabrielsclimaco** [comment]
+1

**Comment by rhuckey** [comment]
How can I get the version with the volume control?

**Comment by vivekbharatha** [comment]
@rhuckey , You can build from my [repo](https://github.com/vivekbharatha/coffitivity-offline), else ill make a build and commit to my [repo's](https://github.com/vivekbharatha/coffitivity-offline) master.
Your call :)

**Comment by siwalikm** [comment]
Thanks for raising the PR @vivekbharatha! I'll check and merge this with the next release.

**Comment by siwalikm** [comment]
@vivekbharatha your commit couldn't be merged due to slider drag bug (see image below).
Please update this PR with the fix for this issue if you can.

Image

**Comment by vivekbharatha** [comment]
Hi @siwalikm , thank you for reviewing.
I have fixed the bug and made few tweaks for better experience.
Here it is #14 .

**Comment by siwalikm** [comment]
Hi @vivekbharatha,
Thanks for the contribution! I'll check out the fix soon and merge it to our working branch if everything is fine 🤞. By the way are you running a windows system?

**Comment by vivekbharatha** [comment]
Nope, I am using mac seirra.
I finally tested the built application before committing. Please correct me if there is anything.
Am always up for contributing to side projects 😁

**Pull request merged**
